package com.taskmate.domain;

import java.time.OffsetDateTime;
import java.util.List;
import java.util.UUID;

//import javax.persistence.PrePersist;
//import javax.persistence.PreUpdate;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "epic")
@Data
public class Epic{

	@DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private UUID epicId;

	@DynamoDBAttribute
    private String epicName;
	
	@DynamoDBAttribute
	private List<Story> stories;

	@DynamoDBAttribute
    private Boolean isActive;

	@DynamoDBAttribute
    private Boolean isPrivate;

	@DynamoDBAttribute
    private Boolean hasChild;

	@DynamoDBAttribute
    private String status;

	@DynamoDBAttribute
    private User createdBy;

	@DynamoDBAttribute
    private OffsetDateTime dateCreated;

	@DynamoDBAttribute
    private OffsetDateTime lastUpdated;

//    @PrePersist
//    public void prePersist() {
//        dateCreated = OffsetDateTime.now();
//        lastUpdated = dateCreated;
//    }
//
//    @PreUpdate
//    public void preUpdate() {
//        lastUpdated = OffsetDateTime.now();
//    }

}
