package com.taskmate.domain;

import java.time.OffsetDateTime;
import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "project")
public class Project{

	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	private Long projectId;

	@DynamoDBAttribute
	private String projectName;

	@DynamoDBAttribute
	private User projectOwner;
	@DynamoDBAttribute
	private OffsetDateTime dateCreated;
	@DynamoDBAttribute
	private OffsetDateTime lastUpdated;
	@DynamoDBAttribute
	private List<Team> teams;

//    @PrePersist
//    public void prePersist() {
//        dateCreated = OffsetDateTime.now();
//        lastUpdated = dateCreated;
//    }
//
//    @PreUpdate
//    public void preUpdate() {
//        lastUpdated = OffsetDateTime.now();
//    }

}
