package com.taskmate.domain;

import java.beans.Transient;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConvertedEnum;
import com.taskmate.utils.EnumUtils.UserType;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@NoArgsConstructor
@Data
@Builder
@DynamoDBTable(tableName = "users")
public class User {

	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	private String userId;

	@DynamoDBAttribute
	private String firstName;

	@DynamoDBAttribute
	private String lastName;

	@DynamoDBAttribute
	private String userName;

	@DynamoDBAttribute
	private String email;

	@DynamoDBTypeConvertedEnum
	@DynamoDBAttribute
	private UserType userType;

	// @DynamoDBAttribute
	// private UUID teamId;

	@DynamoDBAttribute
	private String password;
	
	private String action;

	// @DynamoDBAttribute
	// private OffsetDateTime dateCreated;

	// @DynamoDBAttribute
	// private OffsetDateTime lastUpdated;

//    @PrePersist
//    public void prePersist() {
//        dateCreated = OffsetDateTime.now();
//        lastUpdated = dateCreated;
//    }
//
//    @PreUpdate
//    public void preUpdate() {
//        lastUpdated = OffsetDateTime.now();
//    }

}
